<?php

/**
 * @file
 * Contains e_invoice_cr.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function e_invoice_cr_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the e_invoice_cr module.
    case 'help.page.e_invoice_cr':
      e_invoice_cr_check_java();
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides an invoice system according to the costa rican regulations.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function e_invoice_cr_theme() {
  return [
    'e_invoice_cr' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function e_invoice_cr_preprocess_page(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  if (strpos($current_path, 'e-invoice-cr') || strpos($current_path, 'e_invoice_cr')) {
    e_invoice_cr_check_java();
  }
}

/**
 * Custom function to check if java is available on the server.
 */
function e_invoice_cr_check_java() {
  $error_message = t('Invoice CR Module: Java not detected on the server. This module needs java installed to work properly.');
  $command = 'java -version && echo 1 || echo 0';
  $result = exec($command, $response);
  if(!$result) {
    drupal_set_message($error_message, 'error');
  }
}
