<?php

/**
 * @file
 * Contains e_invoice_cr.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function e_invoice_cr_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the e_invoice_cr module.
    case 'help.page.e_invoice_cr':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides an invoice system according to the costa rican regulations.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function e_invoice_cr_theme() {
  return [
    'e_invoice_cr' => [
      'render element' => 'children',
    ],
  ];
}


