<?php

/**
 * @file
 * Contains tax_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tax_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tax_entity module.
    case 'help.page.tax_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides the tax entity for e-invoice.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tax_entity_theme() {
  return [
    'tax_entity' => [
      'render element' => 'children',
    ],
  ];
}
