<?php

/**
 * @file
 * Contains invoice_email.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function invoice_email_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the invoice_email module.
    case 'help.page.invoice_email':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides the email services functionality to send the invoice PDF file to client.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail().
 */
function invoice_email_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];
  switch ($key) {
    case 'invoice_validated':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Subject: @title', ['@title' => $params['title']], $options);
      $message['body'][] = Html::escape($params['message']);
      break;
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function invoice_email_theme_registry_alter(&$theme_registry) {
  // Change the default template.
  $theme_registry['entity_print']['path'] = drupal_get_path('module', 'invoice_email') . '/templates';
}

/**
 * Implements hook_link_alter().
 */
function invoice_email_link_alter(&$variables) {
  $url = $variables['url'];
  $external = $url->isExternal();
  if ($external == FALSE) {
    $name = $url->getRouteName();
    if ($name === "entity_print.view") {
      $param = $url->getRouteParameters();
      if ($param['entity_type'] === "invoice_entity") {
        // Add a query parameter to the url.
        $url->setRouteParameter('orientation', "landscape");
        $query['orientation'] = "landscape";
        $url->setOption('query', $query);
        $variables['url'] = $url;
      }
    }
  }
}
