<?php

/**
 * @file
 * Contains invoice_email.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function invoice_email_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the invoice_email module.
    case 'help.page.invoice_email':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides the email services functionality to send the invoice PDF file to client.') . '</p>';
      return $output;

    default:
  }
}
