<?php

/**
 * @file
 * Contains invoice_received_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function invoice_received_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the invoice_received_entity module.
    case 'help.page.invoice_received_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides the invoice received entity for e-invoice.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function invoice_received_entity_entity_operation_alter(array &$operations, EntityInterface $entity) {

  if ($entity->getEntityTypeId() === 'invoice_received_entity') {
    if (!is_null($entity->get('field_ir_message')->value) && $entity->get('field_ir_status')->value > 1) {
      unset($operations['edit']);
    }
    else {
      $operations['edit']['title'] = t('Accept or Reject');
    }

    $operations['view'] = [
      'title' => t('View'),
      'weight' => 20,
      'url' => $entity->toUrl(),
    ];
  }
}

/**
 * Implements invoice_received_entity_cron().
 */
function invoice_received_entity_cron() {
  // All the data of the IMAP configuration is obtained.
  $settings = \Drupal::config('imap_settings.settings');
  $remote = $settings->get('remote');
  $port = $settings->get('port');
  $flag = $settings->get('flag');
  $mailbox = $settings->get('mailbox');
  $imap = '{' . $remote . ':' . $port . $flag . '}' . $mailbox;
  $username = $settings->get('username');
  $password = $settings->get('password');
  // The data is passed (with its respective structure) per parameter to the
  // function imap_open.
  $inbox = imap_open($imap, $username, $password);
  // Check if the connection to the mailbox was successful.
  if (!is_null($inbox)) {
    $importXml = \Drupal::service('invoice_received.service');
    // Filtered search to obtain the id of each mail.
    $emails = imap_search($inbox, 'ALL UNSEEN');
    // Check if exists any unseed mail.
    if ($emails) {
      // The routes of all the XML files that were attached to each mail
      // are obtained.
      $paths = $importXml->getXMLFilesFromEmails($inbox, $emails);
      foreach ($paths as $path) {
        // The content of the XML is obtained.
        $xml_content = file_get_contents($path);
        $simpleXml = simplexml_load_string($xml_content);
        // Check if the file has the correct format and not exists the
        // invoice key in the system.
        if (isset($simpleXml->Emisor->Identificacion->Numero) && !$importXml->alreadyExistInvoiceReceivedEntity($simpleXml->Clave)) {
          $importXml->createInvoiceReceivedEntityFromXML($simpleXml);
        }
        // Check if the file has the correct format and not exists the
        // provider ID in the system.
        if (isset($simpleXml->Emisor->Identificacion->Numero) && !$importXml->alreadyExistProviderEntity($simpleXml->Emisor->Identificacion->Numero)) {
          $importXml->createProviderEntityFromXML($simpleXml);
        }
      }
      drupal_set_message($this->t('The XML file(s) was imported successfully from unread email(s).'));
    }
    else {
      drupal_set_message($this->t('No have new unreads emails for XML import.'));
    }
  }
  return $this->redirect('entity.invoice_received_entity.collection');
}